version: "3.8"
services:
  simple-sound-bot:
    build: .
    volumes:
      - ./cache:/root/simple-sound-bot/cache
      - ~/.aws:/root/.aws
    env_file: .env
    command: npm run start -- $${CMD_ARGUMENTS}
    