version: "3.8"
services:
  simple-sound-bot:
    build:
        context: ./docker
        dockerfile: Dockerfile
    volumes:
      - ./cache:/root/simple-sound-bot/cache
      - ~/.aws:/root/.aws
    env_file: .env
    environment:
      - CMD_ARGUMENTS=${CMD_ARGUMENTS}
